apiVersion: v1
kind: Service
metadata:
  name: {{ include "schema-registry.fullname" . }}
  labels:
    {{- include "schema-registry.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: grpc
  selector:
    {{- include "schema-registry.selectorLabels" . | nindent 4 }}
