version: '3.1'

#Use to test docker build/run locally
services:
  app:
    image: apicurio/apicurio-registry-sql:latest
    ports:
      - 8080:8080
    environment:
      - REGISTRY_DATASOURCE_URL=<replace-with-jdbc-spanner-url>
      - GOOGLE_APPLICATION_CREDENTIALS=/config/es-s2-eval-d-5429b0b50112.json
    volumes:
    - /path/to/es-s2-eval-d-5429b0b50112.json:/config/es-s2-eval-d-5429b0b50112.json
